### ISSUE TITLE
version Tag

### ISSUE THREAD

**Issue by ebirn** [BioMedIA/IRTK#2]
Please add version tags to this repository, I am working on EasyBuild integration for this (an automated build system for HPC clusters, see http://hpcugent.github.io/easybuild/).

Having the versions tagged in the repository enables to keep (or build, if necessary) previous released versions of the code, enabling us to reproduce results of previous uses of this software. thx.

**Comment by sk1712** [comment]
Tagged first release https://github.com/BioMedIA/IRTK/releases/tag/v1.0
